// Mock data for development without backend/RELION
import {
  Job,
  JobType,
  JobParameter,
  Pipeline,
  PipelineProcess,
  ProcessStatus,
  ProcessLog,
} from '../types/relion';

// Helper to create common parameters
const createCommonParameters = (): JobParameter[] => [
  {
    label: 'Number of MPI procs',
    variable: 'nr_mpi',
    value: 1,
    type: 'SLIDER',
    minValue: 1,
    maxValue: 64,
    stepValue: 1,
    helpText: 'Number of MPI processes to use',
  },
  {
    label: 'Number of threads',
    variable: 'nr_threads',
    value: 1,
    type: 'SLIDER',
    minValue: 1,
    maxValue: 32,
    stepValue: 1,
    helpText: 'Number of threads per MPI process',
  },
];

// Job templates for each job type
export const mockJobTemplates: Record<JobType, Job> = {
  [JobType.IMPORT]: {
    type: JobType.IMPORT,
    name: 'job001',
    alias: 'Import movies',
    outputDir: 'Import/job001',
    queueSubmit: false,
    nrMpi: 1,
    nrThreads: 1,
    parameters: [
      {
        label: 'Raw input files',
        variable: 'fn_in_raw',
        value: '',
        type: 'FILENAME',
        helpText: 'Provide a Linux wildcard pattern for raw movies/micrographs (e.g., Movies/*.tiff)',
        pattern: '.*',
      },
      {
        label: 'Import raw movies?',
        variable: 'is_raw_movies',
        value: true,
        type: 'BOOLEAN',
        helpText: 'Set to Yes if you want to import raw movie frames',
      },
      {
        label: 'Pixel size (Angstrom)',
        variable: 'angpix',
        value: 1.0,
        type: 'SLIDER',
        minValue: 0.1,
        maxValue: 10.0,
        stepValue: 0.01,
        helpText: 'Pixel size in Angstroms',
      },
      {
        label: 'Voltage (kV)',
        variable: 'kV',
        value: 300,
        type: 'SLIDER',
        minValue: 100,
        maxValue: 400,
        stepValue: 10,
        helpText: 'Acceleration voltage in kV',
      },
      {
        label: 'Spherical aberration (mm)',
        variable: 'Cs',
        value: 2.7,
        type: 'SLIDER',
        minValue: 0,
        maxValue: 5,
        stepValue: 0.1,
        helpText: 'Spherical aberration in mm',
      },
      {
        label: 'Amplitude contrast',
        variable: 'Q0',
        value: 0.1,
        type: 'SLIDER',
        minValue: 0,
        maxValue: 0.3,
        stepValue: 0.01,
        helpText: 'Amplitude contrast (typically 0.07-0.1)',
      },
      {
        label: 'Beamtilt X (mrad)',
        variable: 'beamtilt_x',
        value: 0,
        type: 'SLIDER',
        minValue: -5,
        maxValue: 5,
        stepValue: 0.1,
        helpText: 'Beam tilt in X direction',
      },
      {
        label: 'Beamtilt Y (mrad)',
        variable: 'beamtilt_y',
        value: 0,
        type: 'SLIDER',
        minValue: -5,
        maxValue: 5,
        stepValue: 0.1,
        helpText: 'Beam tilt in Y direction',
      },
    ],
  },

  [JobType.MOTIONCORR]: {
    type: JobType.MOTIONCORR,
    name: 'job002',
    alias: 'Motion correction',
    outputDir: 'MotionCorr/job002',
    queueSubmit: false,
    nrMpi: 1,
    nrThreads: 4,
    parameters: [
      {
        label: 'Input movies STAR file',
        variable: 'fn_in',
        value: '',
        type: 'INPUTNODE',
        helpText: 'STAR file with all input micrographs/movies',
        nodeType: 'MicrographsMovies.star',
      },
      {
        label: 'Motion correction program',
        variable: 'do_own',
        value: 'RELION',
        type: 'RADIO',
        options: ['RELION', 'MotionCor2'],
        helpText: 'Which motion correction algorithm to use',
      },
      {
        label: 'B-factor',
        variable: 'bfactor',
        value: 150,
        type: 'SLIDER',
        minValue: 0,
        maxValue: 500,
        stepValue: 10,
        helpText: 'B-factor for dose weighting',
      },
      {
        label: 'Number of patches X',
        variable: 'patch_x',
        value: 5,
        type: 'SLIDER',
        minValue: 1,
        maxValue: 10,
        stepValue: 1,
        helpText: 'Number of patches in X direction',
      },
      {
        label: 'Number of patches Y',
        variable: 'patch_y',
        value: 5,
        type: 'SLIDER',
        minValue: 1,
        maxValue: 10,
        stepValue: 1,
        helpText: 'Number of patches in Y direction',
      },
      {
        label: 'Group frames',
        variable: 'group_frames',
        value: 1,
        type: 'SLIDER',
        minValue: 1,
        maxValue: 10,
        stepValue: 1,
        helpText: 'Group this many frames for alignment',
      },
      {
        label: 'Binning factor',
        variable: 'bin_factor',
        value: 1,
        type: 'SLIDER',
        minValue: 1,
        maxValue: 4,
        stepValue: 1,
        helpText: 'Binning factor for output micrographs',
      },
      {
        label: 'Gain reference',
        variable: 'fn_gain_ref',
        value: '',
        type: 'FILENAME',
        helpText: 'Gain reference image (optional)',
      },
      {
        label: 'Dose per frame (e/A^2)',
        variable: 'dose_per_frame',
        value: 1.0,
        type: 'SLIDER',
        minValue: 0.1,
        maxValue: 5,
        stepValue: 0.1,
        helpText: 'Dose per frame in electrons per Angstrom squared',
      },
      {
        label: 'Group frames for power spectra',
        variable: 'grouping_for_ps',
        value: -1,
        type: 'SLIDER',
        minValue: -1,
        maxValue: 100,
        stepValue: 1,
        helpText: 'Group this number of frames and write summed power spectrum. -1 = do not write',
      },
      ...createCommonParameters(),
    ],
  },

  [JobType.CTFFIND]: {
    type: JobType.CTFFIND,
    name: 'job003',
    alias: 'CTF estimation',
    outputDir: 'CtfFind/job003',
    queueSubmit: false,
    nrMpi: 1,
    nrThreads: 1,
    parameters: [
      {
        label: 'Input micrographs STAR file',
        variable: 'fn_in',
        value: '',
        type: 'INPUTNODE',
        helpText: 'STAR file with all input micrographs',
        nodeType: 'Micrographs.star',
      },
      {
        label: 'Use CTFFIND4',
        variable: 'is_ctffind4',
        value: true,
        type: 'BOOLEAN',
        helpText: 'Use CTFFIND4 (version 4.1+)',
      },
      {
        label: 'FFT box size (pix)',
        variable: 'Box',
        value: 512,
        type: 'SLIDER',
        minValue: 128,
        maxValue: 1024,
        stepValue: 64,
        helpText: 'Size of FFT box for CTF estimation',
      },
      {
        label: 'Minimum resolution (A)',
        variable: 'ResMin',
        value: 30,
        type: 'SLIDER',
        minValue: 10,
        maxValue: 100,
        stepValue: 5,
        helpText: 'Minimum resolution for CTF fitting',
      },
      {
        label: 'Maximum resolution (A)',
        variable: 'ResMax',
        value: 5,
        type: 'SLIDER',
        minValue: 2,
        maxValue: 20,
        stepValue: 0.5,
        helpText: 'Maximum resolution for CTF fitting',
      },
      {
        label: 'Minimum defocus (A)',
        variable: 'dFMin',
        value: 5000,
        type: 'SLIDER',
        minValue: 1000,
        maxValue: 50000,
        stepValue: 1000,
        helpText: 'Minimum defocus value to search',
      },
      {
        label: 'Maximum defocus (A)',
        variable: 'dFMax',
        value: 50000,
        type: 'SLIDER',
        minValue: 5000,
        maxValue: 100000,
        stepValue: 1000,
        helpText: 'Maximum defocus value to search',
      },
      {
        label: 'Defocus step (A)',
        variable: 'FStep',
        value: 500,
        type: 'SLIDER',
        minValue: 100,
        maxValue: 2000,
        stepValue: 100,
        helpText: 'Step size for defocus search',
      },
      {
        label: 'Amount of astigmatism (A)',
        variable: 'dAst',
        value: 100,
        type: 'SLIDER',
        minValue: 0,
        maxValue: 2000,
        stepValue: 50,
        helpText: 'Amount of astigmatism',
      },
      {
        label: 'Spherical aberration (mm)',
        variable: 'CS',
        value: 2.7,
        type: 'SLIDER',
        minValue: 0,
        maxValue: 5,
        stepValue: 0.1,
        helpText: 'Spherical aberration of the microscope',
      },
      {
        label: 'Voltage (kV)',
        variable: 'HT',
        value: 300,
        type: 'SLIDER',
        minValue: 100,
        maxValue: 300,
        stepValue: 100,
        helpText: 'Acceleration voltage of the microscope',
      },
      {
        label: 'Amplitude contrast',
        variable: 'AmpCnst',
        value: 0.1,
        type: 'SLIDER',
        minValue: 0,
        maxValue: 0.3,
        stepValue: 0.01,
        helpText: 'Amplitude contrast (typically 0.07-0.1)',
      },
      {
        label: 'Pixel size (A)',
        variable: 'angpix',
        value: 1.0,
        type: 'SLIDER',
        minValue: 0.5,
        maxValue: 5,
        stepValue: 0.1,
        helpText: 'Pixel size of the micrographs',
      },
      {
        label: 'Estimate phase shifts?',
        variable: 'do_phaseshift',
        value: false,
        type: 'BOOLEAN',
        helpText: 'Estimate phase shifts (for phase plate data)',
      },
      ...createCommonParameters(),
    ],
  },

  [JobType.MANUALPICK]: {
    type: JobType.MANUALPICK,
    name: 'job004',
    alias: 'Manual picking',
    outputDir: 'ManualPick/job004',
    queueSubmit: false,
    nrMpi: 1,
    nrThreads: 1,
    parameters: [
      {
        label: 'Input micrographs',
        variable: 'fn_in',
        value: '',
        type: 'INPUTNODE',
        helpText: 'STAR file with input micrographs',
        nodeType: 'Micrographs.star',
      },
      {
        label: 'Particle diameter (A)',
        variable: 'diameter',
        value: 200,
        type: 'SLIDER',
        minValue: 10,
        maxValue: 1000,
        stepValue: 10,
        helpText: 'Approximate particle diameter in Angstroms',
      },
      {
        label: 'Lowpass filter (A)',
        variable: 'lowpass',
        value: 20,
        type: 'SLIDER',
        minValue: 5,
        maxValue: 100,
        stepValue: 5,
        helpText: 'Lowpass filter for display',
      },
      {
        label: 'Highpass filter (A)',
        variable: 'highpass',
        value: -1,
        type: 'SLIDER',
        minValue: -1,
        maxValue: 1000,
        stepValue: 10,
        helpText: 'Highpass filter for display (-1 = none)',
      },
      {
        label: 'Scale for micrographs',
        variable: 'angpix_ref',
        value: -1,
        type: 'SLIDER',
        minValue: -1,
        maxValue: 10,
        stepValue: 0.1,
        helpText: 'Pixel size for rescaling (-1 = use original)',
      },
      {
        label: 'Blue/red color scale',
        variable: 'color_scale',
        value: false,
        type: 'BOOLEAN',
        helpText: 'Use blue-red color scale instead of grayscale',
      },
    ],
  },

  [JobType.AUTOPICK]: {
    type: JobType.AUTOPICK,
    name: 'job005',
    alias: 'Auto-picking',
    outputDir: 'AutoPick/job005',
    queueSubmit: false,
    nrMpi: 1,
    nrThreads: 1,
    parameters: [
      {
        label: 'Input micrographs for autopick',
        variable: 'fn_in',
        value: '',
        type: 'INPUTNODE',
        helpText: 'STAR file with input micrographs',
        nodeType: 'Micrographs.star',
      },
      {
        label: 'Use LoG-based picking',
        variable: 'LoG',
        value: true,
        type: 'BOOLEAN',
        helpText: 'Use Laplacian-of-Gaussian filter-based picking',
      },
      {
        label: 'Min. diameter for LoG filter (A)',
        variable: 'LoG_diam_min',
        value: 150,
        type: 'SLIDER',
        minValue: 10,
        maxValue: 500,
        stepValue: 10,
        helpText: 'Smallest particle diameter for blob-detection',
      },
      {
        label: 'Max. diameter for LoG filter (A)',
        variable: 'LoG_diam_max',
        value: 180,
        type: 'SLIDER',
        minValue: 10,
        maxValue: 1000,
        stepValue: 10,
        helpText: 'Largest particle diameter for blob-detection',
      },
      {
        label: 'Adjust threshold (+ less, - more)',
        variable: 'LoG_adjust_threshold',
        value: 0,
        type: 'SLIDER',
        minValue: -5,
        maxValue: 5,
        stepValue: 0.5,
        helpText: 'Adjust the picking threshold: positive for less particles, negative for more',
      },
      {
        label: 'Neighbour distance (%)',
        variable: 'LoG_neighbour',
        value: 100,
        type: 'SLIDER',
        minValue: 10,
        maxValue: 200,
        stepValue: 10,
        helpText: 'Avoid neighbouring particles within this percentage of diameter',
      },
      {
        label: 'Picking threshold',
        variable: 'threshold',
        value: 0.05,
        type: 'SLIDER',
        minValue: 0,
        maxValue: 1,
        stepValue: 0.05,
        helpText: 'Fraction of expected probability ratio for peaks',
      },
      {
        label: 'Pixel size (A)',
        variable: 'angpix',
        value: 1.0,
        type: 'SLIDER',
        minValue: 0.5,
        maxValue: 5,
        stepValue: 0.1,
        helpText: 'Pixel size of the micrographs',
      },
      ...createCommonParameters(),
    ],
  },

  [JobType.EXTRACT]: {
    type: JobType.EXTRACT,
    name: 'job006',
    alias: 'Particle extraction',
    outputDir: 'Extract/job006',
    queueSubmit: false,
    nrMpi: 1,
    nrThreads: 1,
    parameters: [
      {
        label: 'Micrograph STAR file',
        variable: 'i',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Input micrographs STAR file (with CTF info)',
        nodeType: 'Micrographs.star',
      },
      {
        label: 'Coordinate directory',
        variable: 'coord_dir',
        value: '',
        type: 'DIRECTORY',
        helpText: 'Directory containing coordinate files (e.g., AutoPick/job005/)',
      },
      {
        label: 'Coordinate file suffix',
        variable: 'coord_suffix',
        value: '_autopick.star',
        type: 'ANY',
        helpText: 'Suffix of coordinate files (e.g., _autopick.star)',
      },
      {
        label: 'Extract particles?',
        variable: 'extract',
        value: true,
        type: 'BOOLEAN',
        helpText: 'Extract particles from micrographs (required for extraction)',
      },
      {
        label: 'Particle box size (pix)',
        variable: 'extract_size',
        value: 256,
        type: 'SLIDER',
        minValue: 32,
        maxValue: 1024,
        stepValue: 16,
        helpText: 'Size of extracted particle images in pixels',
      },
      {
        label: 'Rescale size (pix)',
        variable: 'scale',
        value: -1,
        type: 'SLIDER',
        minValue: -1,
        maxValue: 512,
        stepValue: 16,
        helpText: 'Rescale particles to this size (-1 = no rescaling)',
      },
      {
        label: 'Invert contrast?',
        variable: 'invert_contrast',
        value: false,
        type: 'BOOLEAN',
        helpText: 'Invert contrast (for negative stain or some cryo data)',
      },
      {
        label: 'Normalize particles?',
        variable: 'norm',
        value: true,
        type: 'BOOLEAN',
        helpText: 'Normalize particle images',
      },
      {
        label: 'Background radius (pix)',
        variable: 'bg_radius',
        value: -1,
        type: 'SLIDER',
        minValue: -1,
        maxValue: 500,
        stepValue: 10,
        helpText: 'Radius for background normalization (-1 = auto-calculate as 75% of box radius)',
      },
      {
        label: 'Stddev for white dust removal',
        variable: 'white_dust',
        value: -1,
        type: 'SLIDER',
        minValue: -1,
        maxValue: 10,
        stepValue: 0.5,
        helpText: 'Standard deviation for white dust removal (-1 = no)',
      },
      {
        label: 'Stddev for black dust removal',
        variable: 'black_dust',
        value: -1,
        type: 'SLIDER',
        minValue: -1,
        maxValue: 10,
        stepValue: 0.5,
        helpText: 'Standard deviation for black dust removal (-1 = no)',
      },
      ...createCommonParameters(),
    ],
  },

  [JobType.CLASS2D]: {
    type: JobType.CLASS2D,
    name: 'job007',
    alias: '2D classification',
    outputDir: 'Class2D/job007',
    queueSubmit: false,
    nrMpi: 4,
    nrThreads: 4,
    parameters: [
      {
        label: 'Input images STAR file',
        variable: 'fn_img',
        value: '',
        type: 'INPUTNODE',
        helpText: 'STAR file with input particles',
        nodeType: 'Particles.star',
      },
      {
        label: 'Number of classes',
        variable: 'nr_classes',
        value: 50,
        type: 'SLIDER',
        minValue: 1,
        maxValue: 200,
        stepValue: 1,
        helpText: 'Number of 2D classes',
      },
      {
        label: 'Regularisation parameter T',
        variable: 'tau_fudge',
        value: 2,
        type: 'SLIDER',
        minValue: 1,
        maxValue: 8,
        stepValue: 0.5,
        helpText: 'Regularisation parameter (2-4 for 2D)',
      },
      {
        label: 'Number of iterations',
        variable: 'nr_iter',
        value: 25,
        type: 'SLIDER',
        minValue: 1,
        maxValue: 50,
        stepValue: 1,
        helpText: 'Number of EM iterations',
      },
      {
        label: 'Mask diameter (A)',
        variable: 'particle_diameter',
        value: 200,
        type: 'SLIDER',
        minValue: 10,
        maxValue: 1000,
        stepValue: 10,
        helpText: 'Circular mask diameter in Angstroms',
      },
      {
        label: 'Use GPU acceleration?',
        variable: 'use_gpu',
        value: true,
        type: 'BOOLEAN',
        helpText: 'Use GPU for classification',
      },
      {
        label: 'Which GPUs to use',
        variable: 'gpu_ids',
        value: '0',
        type: 'ANY',
        helpText: 'GPU device IDs (e.g., 0,1,2)',
      },
      {
        label: 'Ignore CTF until first peak?',
        variable: 'ctf_intact_first_peak',
        value: false,
        type: 'BOOLEAN',
        helpText: 'Ignore CTF until first peak',
      },
      {
        label: 'Do center classes?',
        variable: 'do_center',
        value: true,
        type: 'BOOLEAN',
        helpText: 'Center class averages',
      },
      ...createCommonParameters(),
    ],
  },

  [JobType.CLASS3D]: {
    type: JobType.CLASS3D,
    name: 'job008',
    alias: '3D classification',
    outputDir: 'Class3D/job008',
    queueSubmit: false,
    nrMpi: 4,
    nrThreads: 4,
    parameters: [
      {
        label: 'Input images STAR file',
        variable: 'fn_img',
        value: '',
        type: 'INPUTNODE',
        helpText: 'STAR file with input particles',
        nodeType: 'Particles.star',
      },
      {
        label: 'Reference map',
        variable: 'fn_ref',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Reference map for 3D classification',
        nodeType: 'Reference3D.mrc',
        optional: true,
      },
      {
        label: 'Number of classes',
        variable: 'nr_classes',
        value: 4,
        type: 'SLIDER',
        minValue: 1,
        maxValue: 20,
        stepValue: 1,
        helpText: 'Number of 3D classes',
      },
      {
        label: 'Regularisation parameter T',
        variable: 'tau_fudge',
        value: 4,
        type: 'SLIDER',
        minValue: 1,
        maxValue: 8,
        stepValue: 0.5,
        helpText: 'Regularisation parameter (4 for 3D)',
      },
      {
        label: 'Number of iterations',
        variable: 'nr_iter',
        value: 25,
        type: 'SLIDER',
        minValue: 1,
        maxValue: 50,
        stepValue: 1,
        helpText: 'Number of EM iterations',
      },
      {
        label: 'Mask diameter (A)',
        variable: 'particle_diameter',
        value: 200,
        type: 'SLIDER',
        minValue: 10,
        maxValue: 1000,
        stepValue: 10,
        helpText: 'Mask diameter in Angstroms',
      },
      {
        label: 'Initial angular sampling (healpix order)',
        variable: 'healpix_order',
        value: 2,
        type: 'SLIDER',
        minValue: 0,
        maxValue: 5,
        stepValue: 1,
        helpText: 'Healpix order for angular sampling: 0=30°, 1=15°, 2=7.5°, 3=3.7°, 4=1.8°, 5=0.9°',
      },
      {
        label: 'Symmetry',
        variable: 'sym_name',
        value: 'C1',
        type: 'ANY',
        helpText: 'Point group symmetry (C1, C2, D2, etc.)',
      },
      {
        label: 'Use GPU acceleration?',
        variable: 'use_gpu',
        value: true,
        type: 'BOOLEAN',
        helpText: 'Use GPU for classification',
      },
      {
        label: 'Which GPUs to use',
        variable: 'gpu_ids',
        value: '0',
        type: 'ANY',
        helpText: 'GPU device IDs',
      },
      {
        label: 'Trust reference size?',
        variable: 'trust_ref_size',
        value: false,
        type: 'BOOLEAN',
        helpText: 'Allow reference with different pixel/box size than particles (will rescale automatically)',
      },
      ...createCommonParameters(),
    ],
  },

  [JobType.REFINE3D]: {
    type: JobType.REFINE3D,
    name: 'job009',
    alias: '3D auto-refine',
    outputDir: 'Refine3D/job009',
    queueSubmit: false,
    nrMpi: 5,
    nrThreads: 2,
    parameters: [
      {
        label: 'Input images STAR file',
        variable: 'fn_img',
        value: '',
        type: 'INPUTNODE',
        helpText: 'STAR file with input particles',
        nodeType: 'Particles.star',
      },
      {
        label: 'Reference map',
        variable: 'fn_ref',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Reference map for refinement',
        nodeType: 'Reference3D.mrc',
      },
      {
        label: 'Initial lowpass filter (A)',
        variable: 'ini_high',
        value: 60,
        type: 'SLIDER',
        minValue: 10,
        maxValue: 100,
        stepValue: 5,
        helpText: 'Initial lowpass filter on reference',
      },
      {
        label: 'Mask diameter (A)',
        variable: 'particle_diameter',
        value: 200,
        type: 'SLIDER',
        minValue: 10,
        maxValue: 1000,
        stepValue: 10,
        helpText: 'Mask diameter in Angstroms',
      },
      {
        label: 'Symmetry',
        variable: 'sym_name',
        value: 'C1',
        type: 'ANY',
        helpText: 'Point group symmetry',
      },
      {
        label: 'Initial angular sampling (healpix order)',
        variable: 'healpix_order',
        value: 2,
        type: 'SLIDER',
        minValue: 0,
        maxValue: 5,
        stepValue: 1,
        helpText: 'Healpix order for angular sampling: 0=30°, 1=15°, 2=7.5°, 3=3.7°, 4=1.8°, 5=0.9°',
      },
      {
        label: 'Local searches from auto-sampling (healpix order)',
        variable: 'auto_local_healpix_order',
        value: 4,
        type: 'SLIDER',
        minValue: 2,
        maxValue: 6,
        stepValue: 1,
        helpText: 'Healpix order for local angular searches: 2=7.5°, 3=3.7°, 4=1.8°, 5=0.9°, 6=0.5°',
      },
      {
        label: 'Use solvent-flattened FSCs?',
        variable: 'do_solvent_fsc',
        value: false,
        type: 'BOOLEAN',
        helpText: 'Calculate gold-standard FSC with solvent mask',
      },
      {
        label: 'Reference mask',
        variable: 'fn_mask',
        value: '',
        type: 'FILENAME',
        helpText: 'Mask for reference (optional)',
        optional: true,
      },
      {
        label: 'Use GPU acceleration?',
        variable: 'use_gpu',
        value: true,
        type: 'BOOLEAN',
        helpText: 'Use GPU for refinement',
      },
      {
        label: 'Which GPUs to use',
        variable: 'gpu_ids',
        value: '0',
        type: 'ANY',
        helpText: 'GPU device IDs',
      },
      {
        label: 'Trust reference size?',
        variable: 'trust_ref_size',
        value: false,
        type: 'BOOLEAN',
        helpText: 'Allow reference with different pixel/box size than particles (will rescale automatically)',
      },
      ...createCommonParameters(),
    ],
  },

  [JobType.MULTIBODY]: {
    type: JobType.MULTIBODY,
    name: 'job010',
    alias: 'Multi-body refinement',
    outputDir: 'MultiBody/job010',
    queueSubmit: false,
    nrMpi: 4,
    nrThreads: 4,
    parameters: [
      {
        label: 'Consensus refinement STAR',
        variable: 'fn_in',
        value: '',
        type: 'INPUTNODE',
        helpText: 'STAR file from consensus refinement',
        nodeType: 'Optimiser.star',
      },
      {
        label: 'Body STAR file',
        variable: 'fn_bodies',
        value: '',
        type: 'FILENAME',
        helpText: 'STAR file defining the bodies',
      },
      {
        label: 'Initial angular sampling (healpix order)',
        variable: 'healpix_order',
        value: 4,
        type: 'SLIDER',
        minValue: 2,
        maxValue: 6,
        stepValue: 1,
        helpText: 'Healpix order for angular sampling: 2=7.5°, 3=3.7°, 4=1.8°, 5=0.9°',
      },
      {
        label: 'Use GPU acceleration?',
        variable: 'use_gpu',
        value: true,
        type: 'BOOLEAN',
        helpText: 'Use GPU',
      },
      ...createCommonParameters(),
    ],
  },

  [JobType.CTFREFINE]: {
    type: JobType.CTFREFINE,
    name: 'job011',
    alias: 'CTF refinement',
    outputDir: 'CtfRefine/job011',
    queueSubmit: false,
    nrMpi: 4,
    nrThreads: 4,
    parameters: [
      {
        label: 'Particles STAR file',
        variable: 'fn_data',
        value: '',
        type: 'INPUTNODE',
        helpText: 'STAR file with particles',
        nodeType: 'Particles.star',
      },
      {
        label: 'Postprocess STAR file',
        variable: 'fn_post',
        value: '',
        type: 'INPUTNODE',
        helpText: 'STAR file from PostProcess',
        nodeType: 'PostProcess.star',
        optional: true,
      },
      {
        label: 'Estimate anisotropic magnification?',
        variable: 'do_aniso_mag',
        value: false,
        type: 'BOOLEAN',
        helpText: 'Estimate anisotropic magnification',
      },
      {
        label: 'Estimate beam tilt?',
        variable: 'do_beamtilt',
        value: true,
        type: 'BOOLEAN',
        helpText: 'Estimate beam tilt',
      },
      {
        label: 'Estimate per-particle defocus?',
        variable: 'do_ctf',
        value: true,
        type: 'BOOLEAN',
        helpText: 'Estimate per-particle defocus',
      },
      {
        label: 'Estimate trefoil?',
        variable: 'do_trefoil',
        value: false,
        type: 'BOOLEAN',
        helpText: 'Estimate higher-order aberrations',
      },
      {
        label: 'Estimate 4th order aberrations?',
        variable: 'do_4thorder',
        value: false,
        type: 'BOOLEAN',
        helpText: 'Estimate 4th order aberrations',
      },
      ...createCommonParameters(),
    ],
  },

  [JobType.MOTIONREFINE]: {
    type: JobType.MOTIONREFINE,
    name: 'job012',
    alias: 'Bayesian polishing',
    outputDir: 'MotionRefine/job012',
    queueSubmit: false,
    nrMpi: 4,
    nrThreads: 4,
    parameters: [
      {
        label: 'Particles STAR file',
        variable: 'fn_data',
        value: '',
        type: 'INPUTNODE',
        helpText: 'STAR file with particles',
        nodeType: 'Particles.star',
      },
      {
        label: 'Postprocess STAR file',
        variable: 'fn_post',
        value: '',
        type: 'INPUTNODE',
        helpText: 'STAR file from PostProcess',
        nodeType: 'PostProcess.star',
        optional: true,
      },
      {
        label: 'First movie frame',
        variable: 'first_frame',
        value: 1,
        type: 'SLIDER',
        minValue: 1,
        maxValue: 50,
        stepValue: 1,
        helpText: 'First frame to use',
      },
      {
        label: 'Last movie frame',
        variable: 'last_frame',
        value: -1,
        type: 'SLIDER',
        minValue: -1,
        maxValue: 100,
        stepValue: 1,
        helpText: 'Last frame (-1 = use all)',
      },
      {
        label: 'Fit per-particle motion?',
        variable: 'do_polish',
        value: true,
        type: 'BOOLEAN',
        helpText: 'Fit per-particle motion tracks',
      },
      ...createCommonParameters(),
    ],
  },

  [JobType.POSTPROCESS]: {
    type: JobType.POSTPROCESS,
    name: 'job013',
    alias: 'Post-processing',
    outputDir: 'PostProcess/job013',
    queueSubmit: false,
    nrMpi: 1,
    nrThreads: 1,
    parameters: [
      {
        label: 'One of the 2 unfiltered half-maps',
        variable: 'fn_in',
        value: '',
        type: 'INPUTNODE',
        helpText: 'One of the two unfiltered half-maps',
        nodeType: 'HalfMap.mrc',
      },
      {
        label: 'Solvent mask',
        variable: 'fn_mask',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Mask for solvent correction',
        nodeType: 'Mask.mrc',
        optional: true,
      },
      {
        label: 'MTF of detector (STAR file)',
        variable: 'fn_mtf',
        value: '',
        type: 'FILENAME',
        helpText: 'MTF STAR file for sharpening',
        optional: true,
      },
      {
        label: 'Calibrated pixel size (A)',
        variable: 'angpix',
        value: -1,
        type: 'SLIDER',
        minValue: -1,
        maxValue: 5,
        stepValue: 0.01,
        helpText: 'Calibrated pixel size (-1 = from header)',
      },
      {
        label: 'Ad-hoc B-factor (A^2)',
        variable: 'adhoc_bfac',
        value: 0,
        type: 'SLIDER',
        minValue: -200,
        maxValue: 200,
        stepValue: 10,
        helpText: 'User-provided B-factor (0 = auto)',
      },
      {
        label: 'Skip FSC-weighting?',
        variable: 'do_skip_fsc_weighting',
        value: false,
        type: 'BOOLEAN',
        helpText: 'Skip FSC-based filtering',
      },
      {
        label: 'Low-pass filter (A)',
        variable: 'low_pass',
        value: 5,
        type: 'SLIDER',
        minValue: 2,
        maxValue: 20,
        stepValue: 0.5,
        helpText: 'Resolution for low-pass filtering',
      },
    ],
  },

  [JobType.LOCRES]: {
    type: JobType.LOCRES,
    name: 'job014',
    alias: 'Local resolution',
    outputDir: 'LocalRes/job014',
    queueSubmit: false,
    nrMpi: 1,
    nrThreads: 4,
    parameters: [
      {
        label: 'One of the 2 unfiltered half-maps',
        variable: 'fn_in',
        value: '',
        type: 'INPUTNODE',
        helpText: 'One of the two unfiltered half-maps',
        nodeType: 'HalfMap.mrc',
      },
      {
        label: 'User-provided B-factor (A^2)',
        variable: 'adhoc_bfac',
        value: 0,
        type: 'SLIDER',
        minValue: -200,
        maxValue: 200,
        stepValue: 10,
        helpText: 'B-factor for filtering',
      },
      {
        label: 'Calibrated pixel size (A)',
        variable: 'angpix',
        value: -1,
        type: 'SLIDER',
        minValue: -1,
        maxValue: 5,
        stepValue: 0.01,
        helpText: 'Pixel size (-1 = from header)',
      },
      ...createCommonParameters(),
    ],
  },

  [JobType.MASKCREATE]: {
    type: JobType.MASKCREATE,
    name: 'job015',
    alias: 'Mask creation',
    outputDir: 'MaskCreate/job015',
    queueSubmit: false,
    nrMpi: 1,
    nrThreads: 1,
    parameters: [
      {
        label: 'Input 3D map',
        variable: 'fn_in',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Input map for mask creation',
        nodeType: 'Map.mrc',
      },
      {
        label: 'Lowpass filter (A)',
        variable: 'lowpass_filter',
        value: 15,
        type: 'SLIDER',
        minValue: 5,
        maxValue: 50,
        stepValue: 1,
        helpText: 'Lowpass filter before binarization',
      },
      {
        label: 'Binarization threshold',
        variable: 'threshold',
        value: 0.02,
        type: 'SLIDER',
        minValue: 0.001,
        maxValue: 0.5,
        stepValue: 0.001,
        helpText: 'Threshold for binarization',
      },
      {
        label: 'Extend binary map (pix)',
        variable: 'extend',
        value: 3,
        type: 'SLIDER',
        minValue: 0,
        maxValue: 20,
        stepValue: 1,
        helpText: 'Pixels to extend mask',
      },
      {
        label: 'Add soft edge (pix)',
        variable: 'soft_edge',
        value: 3,
        type: 'SLIDER',
        minValue: 0,
        maxValue: 20,
        stepValue: 1,
        helpText: 'Width of soft edge',
      },
    ],
  },

  [JobType.JOINSTAR]: {
    type: JobType.JOINSTAR,
    name: 'job016',
    alias: 'Join STAR files',
    outputDir: 'JoinStar/job016',
    queueSubmit: false,
    nrMpi: 1,
    nrThreads: 1,
    parameters: [
      {
        label: 'Combine particle STAR files?',
        variable: 'do_part',
        value: true,
        type: 'BOOLEAN',
        helpText: 'Join particle STAR files',
      },
      {
        label: 'Particle STAR file 1',
        variable: 'fn_part1',
        value: '',
        type: 'INPUTNODE',
        helpText: 'First particle STAR file',
        nodeType: 'Particles.star',
      },
      {
        label: 'Particle STAR file 2',
        variable: 'fn_part2',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Second particle STAR file',
        nodeType: 'Particles.star',
      },
      {
        label: 'Combine micrograph STAR files?',
        variable: 'do_mic',
        value: false,
        type: 'BOOLEAN',
        helpText: 'Join micrograph STAR files',
      },
    ],
  },

  [JobType.SUBTRACT]: {
    type: JobType.SUBTRACT,
    name: 'job017',
    alias: 'Particle subtraction',
    outputDir: 'Subtract/job017',
    queueSubmit: false,
    nrMpi: 4,
    nrThreads: 1,
    parameters: [
      {
        label: 'Input particles',
        variable: 'fn_data',
        value: '',
        type: 'INPUTNODE',
        helpText: 'STAR file with input particles',
        nodeType: 'Particles.star',
      },
      {
        label: 'Map to subtract',
        variable: 'fn_in',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Map to project and subtract',
        nodeType: 'Map.mrc',
      },
      {
        label: 'Mask',
        variable: 'fn_mask',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Mask for subtraction region',
        nodeType: 'Mask.mrc',
      },
      {
        label: 'Do center subtracted images?',
        variable: 'do_center',
        value: true,
        type: 'BOOLEAN',
        helpText: 'Center the subtracted particles',
      },
      {
        label: 'New center X (pix)',
        variable: 'center_x',
        value: 0,
        type: 'SLIDER',
        minValue: -100,
        maxValue: 100,
        stepValue: 1,
        helpText: 'X coordinate of new center',
      },
      {
        label: 'New center Y (pix)',
        variable: 'center_y',
        value: 0,
        type: 'SLIDER',
        minValue: -100,
        maxValue: 100,
        stepValue: 1,
        helpText: 'Y coordinate of new center',
      },
      {
        label: 'New center Z (pix)',
        variable: 'center_z',
        value: 0,
        type: 'SLIDER',
        minValue: -100,
        maxValue: 100,
        stepValue: 1,
        helpText: 'Z coordinate of new center',
      },
      ...createCommonParameters(),
    ],
  },

  [JobType.INIMODEL]: {
    type: JobType.INIMODEL,
    name: 'job018',
    alias: 'Initial model',
    outputDir: 'InitialModel/job018',
    queueSubmit: false,
    nrMpi: 4,
    nrThreads: 4,
    parameters: [
      {
        label: 'Input images STAR file',
        variable: 'fn_img',
        value: '',
        type: 'INPUTNODE',
        helpText: 'STAR file with particles for initial model',
        nodeType: 'Particles.star',
      },
      {
        label: 'Number of classes',
        variable: 'nr_classes',
        value: 1,
        type: 'SLIDER',
        minValue: 1,
        maxValue: 10,
        stepValue: 1,
        helpText: 'Number of 3D models to generate',
      },
      {
        label: 'Mask diameter (A)',
        variable: 'particle_diameter',
        value: 200,
        type: 'SLIDER',
        minValue: 10,
        maxValue: 1000,
        stepValue: 10,
        helpText: 'Mask diameter',
      },
      {
        label: 'Symmetry',
        variable: 'sym_name',
        value: 'C1',
        type: 'ANY',
        helpText: 'Point group symmetry',
      },
      {
        label: 'Number of iterations',
        variable: 'nr_iter',
        value: 100,
        type: 'SLIDER',
        minValue: 10,
        maxValue: 200,
        stepValue: 10,
        helpText: 'Number of SGD iterations',
      },
      {
        label: 'Use GPU acceleration?',
        variable: 'use_gpu',
        value: true,
        type: 'BOOLEAN',
        helpText: 'Use GPU',
      },
      {
        label: 'Which GPUs to use',
        variable: 'gpu_ids',
        value: '0',
        type: 'ANY',
        helpText: 'GPU device IDs (e.g., 0,1,2)',
      },
      ...createCommonParameters(),
    ],
  },

  [JobType.CLASSSELECT]: {
    type: JobType.CLASSSELECT,
    name: 'job019',
    alias: 'Subset selection',
    outputDir: 'Select/job019',
    queueSubmit: false,
    nrMpi: 1,
    nrThreads: 1,
    parameters: [
      {
        label: 'Particles from Class2D/3D (run_it*_data.star)',
        variable: 'fn_data',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Use run_it###_data.star from Class2D/Class3D (NOT model.star)',
        nodeType: 'Particles.star',
      },
      {
        label: 'OR micrographs.star',
        variable: 'fn_mic',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Micrograph STAR file for filtering',
        nodeType: 'Micrographs.star',
      },
      {
        label: 'Select by column (e.g., rlnClassNumber)',
        variable: 'select_label',
        value: 'rlnClassNumber',
        type: 'ANY',
        helpText: 'Metadata column to filter on. Use rlnClassNumber for class selection.',
      },
      {
        label: 'Minimum class number',
        variable: 'select_minval',
        value: 1,
        type: 'ANY',
        helpText: 'Select classes >= this value',
      },
      {
        label: 'Maximum class number',
        variable: 'select_maxval',
        value: 10,
        type: 'ANY',
        helpText: 'Select classes <= this value',
      },
    ],
  },

  [JobType.CLASSRANKER]: {
    type: JobType.CLASSRANKER,
    name: 'job020',
    alias: 'Class ranker',
    outputDir: 'ClassRanker/job020',
    queueSubmit: false,
    nrMpi: 1,
    nrThreads: 4,
    parameters: [
      {
        label: 'Select classes from model.star',
        variable: 'fn_model',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Model STAR file from 2D classification',
        nodeType: 'Model.star',
      },
      {
        label: 'Minimum score',
        variable: 'min_score',
        value: 0.5,
        type: 'SLIDER',
        minValue: 0,
        maxValue: 1,
        stepValue: 0.05,
        helpText: 'Minimum predicted score for selection',
      },
      {
        label: 'Select at least this many classes',
        variable: 'select_min_nr',
        value: 1,
        type: 'SLIDER',
        minValue: 1,
        maxValue: 100,
        stepValue: 1,
        helpText: 'Minimum number of classes to select',
      },
      {
        label: 'Use GPU acceleration?',
        variable: 'use_gpu',
        value: true,
        type: 'BOOLEAN',
        helpText: 'Use GPU',
      },
      ...createCommonParameters(),
    ],
  },

  [JobType.MODELANGELO]: {
    type: JobType.MODELANGELO,
    name: 'job021',
    alias: 'ModelAngelo',
    outputDir: 'ModelAngelo/job021',
    queueSubmit: false,
    nrMpi: 1,
    nrThreads: 4,
    parameters: [
      {
        label: 'Input map',
        variable: 'fn_in',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Sharpened map for model building',
        nodeType: 'Map.mrc',
      },
      {
        label: 'FASTA sequence',
        variable: 'fn_fasta',
        value: '',
        type: 'FILENAME',
        helpText: 'FASTA file with protein sequence',
      },
      {
        label: 'Use GPU acceleration?',
        variable: 'use_gpu',
        value: true,
        type: 'BOOLEAN',
        helpText: 'Use GPU',
      },
      ...createCommonParameters(),
    ],
  },

  [JobType.DYNAMIGHT]: {
    type: JobType.DYNAMIGHT,
    name: 'job022',
    alias: 'DynaMight',
    outputDir: 'DynaMight/job022',
    queueSubmit: true,
    nrMpi: 1,
    nrThreads: 4,
    parameters: [
      {
        label: 'Refinement STAR file',
        variable: 'refinement_star',
        value: '',
        type: 'INPUTNODE',
        helpText: 'STAR file from 3D refinement (run_data.star)',
        nodeType: 'Particles.star',
      },
      {
        label: 'Initial model (optional)',
        variable: 'initial_model',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Initial consensus map (optional, will be estimated if not provided)',
        nodeType: 'Map.mrc',
        optional: true,
      },
      {
        label: 'Mask (optional)',
        variable: 'mask_file',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Mask for focused analysis (optional)',
        nodeType: 'Mask.mrc',
        optional: true,
      },
      {
        label: 'Number of Gaussians',
        variable: 'n_gaussians',
        value: 30000,
        type: 'SLIDER',
        minValue: 5000,
        maxValue: 100000,
        stepValue: 5000,
        helpText: 'Number of Gaussian points for representation',
      },
      {
        label: 'Latent dimensions',
        variable: 'n_latent_dimensions',
        value: 6,
        type: 'SLIDER',
        minValue: 2,
        maxValue: 20,
        stepValue: 1,
        helpText: 'Number of latent dimensions (conformational degrees of freedom)',
      },
      {
        label: 'Number of epochs',
        variable: 'n_epochs',
        value: 150,
        type: 'SLIDER',
        minValue: 50,
        maxValue: 500,
        stepValue: 10,
        helpText: 'Number of training epochs',
      },
      {
        label: 'Batch size',
        variable: 'batch_size',
        value: 128,
        type: 'SLIDER',
        minValue: 32,
        maxValue: 512,
        stepValue: 32,
        helpText: 'Batch size for training',
      },
      {
        label: 'Initial resolution (Å)',
        variable: 'initial_resolution',
        value: 8,
        type: 'SLIDER',
        minValue: 4,
        maxValue: 20,
        stepValue: 1,
        helpText: 'Initial resolution for training',
      },
      {
        label: 'Number of linear layers',
        variable: 'n_linear_layers',
        value: 8,
        type: 'SLIDER',
        minValue: 4,
        maxValue: 16,
        stepValue: 1,
        helpText: 'Number of layers in the neural network',
      },
      {
        label: 'Neurons per layer',
        variable: 'n_neurons_per_layer',
        value: 32,
        type: 'SLIDER',
        minValue: 16,
        maxValue: 128,
        stepValue: 8,
        helpText: 'Number of neurons in each layer',
      },
      {
        label: 'Particle diameter (Å)',
        variable: 'particle_diameter',
        value: 200,
        type: 'SLIDER',
        minValue: 50,
        maxValue: 500,
        stepValue: 10,
        helpText: 'Particle diameter for masking',
      },
      {
        label: 'Use GPU partition',
        variable: 'use_gpu_partition',
        value: true,
        type: 'BOOLEAN',
        helpText: 'Submit to GPU partition (required for DynaMight to run properly)',
      },
      {
        label: 'GPU ID',
        variable: 'gpu_id',
        value: 0,
        type: 'SLIDER',
        minValue: 0,
        maxValue: 7,
        stepValue: 1,
        helpText: 'GPU device ID to use',
      },
      {
        label: 'Preload images',
        variable: 'preload_images',
        value: false,
        type: 'BOOLEAN',
        helpText: 'Preload all images into memory (faster but uses more RAM)',
      },
      ...createCommonParameters(),
    ],
  },

  [JobType.EXTERNAL]: {
    type: JobType.EXTERNAL,
    name: 'job023',
    alias: 'External job',
    outputDir: 'External/job023',
    queueSubmit: false,
    nrMpi: 1,
    nrThreads: 1,
    parameters: [
      {
        label: 'External executable',
        variable: 'fn_exe',
        value: '',
        type: 'FILENAME',
        helpText: 'Path to external program',
      },
      {
        label: 'Input file',
        variable: 'fn_in',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Input file for external program (optional)',
        nodeType: 'Any',
        optional: true,
      },
      {
        label: 'Additional arguments',
        variable: 'other_args',
        value: '',
        type: 'ANY',
        helpText: 'Additional command-line arguments',
      },
      ...createCommonParameters(),
    ],
  },

  // Tomography jobs
  [JobType.TOMO_IMPORT]: {
    type: JobType.TOMO_IMPORT,
    name: 'job024',
    alias: 'Import tomo',
    outputDir: 'TomoImport/job024',
    queueSubmit: false,
    nrMpi: 1,
    nrThreads: 1,
    parameters: [
      {
        label: 'Tilt series STAR file or pattern',
        variable: 'fn_in',
        value: '',
        type: 'FILENAME',
        helpText: 'Pattern for tilt series images',
      },
      {
        label: 'Pixel size (A)',
        variable: 'angpix',
        value: 1.0,
        type: 'SLIDER',
        minValue: 0.1,
        maxValue: 10,
        stepValue: 0.01,
        helpText: 'Pixel size in Angstroms',
      },
      {
        label: 'Voltage (kV)',
        variable: 'kV',
        value: 300,
        type: 'SLIDER',
        minValue: 100,
        maxValue: 400,
        stepValue: 10,
        helpText: 'Acceleration voltage',
      },
      {
        label: 'Spherical aberration (mm)',
        variable: 'Cs',
        value: 2.7,
        type: 'SLIDER',
        minValue: 0,
        maxValue: 5,
        stepValue: 0.1,
        helpText: 'Spherical aberration',
      },
    ],
  },

  [JobType.TOMO_EXCLUDETILTS]: {
    type: JobType.TOMO_EXCLUDETILTS,
    name: 'job025',
    alias: 'Exclude tilts',
    outputDir: 'TomoExclude/job025',
    queueSubmit: false,
    nrMpi: 1,
    nrThreads: 1,
    parameters: [
      {
        label: 'Tomograms STAR file',
        variable: 'fn_in',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Input tomograms STAR file',
        nodeType: 'Tomograms.star',
      },
    ],
  },

  [JobType.TOMO_ALIGNTILTS]: {
    type: JobType.TOMO_ALIGNTILTS,
    name: 'job026',
    alias: 'Align tilts',
    outputDir: 'TomoAlign/job026',
    queueSubmit: false,
    nrMpi: 1,
    nrThreads: 4,
    parameters: [
      {
        label: 'Tomograms STAR file',
        variable: 'fn_in',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Input tomograms STAR file',
        nodeType: 'Tomograms.star',
      },
      {
        label: 'Fiducial diameter (A)',
        variable: 'fiducial_diameter',
        value: 100,
        type: 'SLIDER',
        minValue: 10,
        maxValue: 500,
        stepValue: 10,
        helpText: 'Diameter of fiducial markers',
      },
      ...createCommonParameters(),
    ],
  },

  [JobType.TOMO_RECONSTRUCT]: {
    type: JobType.TOMO_RECONSTRUCT,
    name: 'job027',
    alias: 'Reconstruct tomo',
    outputDir: 'TomoReconstruct/job027',
    queueSubmit: false,
    nrMpi: 1,
    nrThreads: 4,
    parameters: [
      {
        label: 'Tomograms STAR file',
        variable: 'fn_in',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Input tomograms STAR file',
        nodeType: 'Tomograms.star',
      },
      {
        label: 'Binning factor',
        variable: 'bin_factor',
        value: 4,
        type: 'SLIDER',
        minValue: 1,
        maxValue: 16,
        stepValue: 1,
        helpText: 'Binning factor for reconstruction',
      },
      {
        label: 'Tomogram thickness (pix)',
        variable: 'thickness',
        value: 500,
        type: 'SLIDER',
        minValue: 100,
        maxValue: 2000,
        stepValue: 50,
        helpText: 'Thickness of reconstructed tomogram',
      },
      ...createCommonParameters(),
    ],
  },

  [JobType.TOMO_DENOISE]: {
    type: JobType.TOMO_DENOISE,
    name: 'job028',
    alias: 'Denoise tomo',
    outputDir: 'TomoDenoise/job028',
    queueSubmit: false,
    nrMpi: 1,
    nrThreads: 4,
    parameters: [
      {
        label: 'Tomograms STAR file',
        variable: 'fn_in',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Input tomograms STAR file',
        nodeType: 'Tomograms.star',
      },
      {
        label: 'Use GPU acceleration?',
        variable: 'use_gpu',
        value: true,
        type: 'BOOLEAN',
        helpText: 'Use GPU',
      },
      ...createCommonParameters(),
    ],
  },

  [JobType.TOMO_IMPORTPARTICLES]: {
    type: JobType.TOMO_IMPORTPARTICLES,
    name: 'job029',
    alias: 'Import tomo particles',
    outputDir: 'TomoImportParticles/job029',
    queueSubmit: false,
    nrMpi: 1,
    nrThreads: 1,
    parameters: [
      {
        label: 'Tomograms STAR file',
        variable: 'fn_tomos',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Tomograms STAR file',
        nodeType: 'Tomograms.star',
      },
      {
        label: 'Coordinates STAR file',
        variable: 'fn_coords',
        value: '',
        type: 'FILENAME',
        helpText: 'Coordinates STAR file',
      },
    ],
  },

  [JobType.TOMO_SUBTOMO]: {
    type: JobType.TOMO_SUBTOMO,
    name: 'job030',
    alias: 'Subtomogram averaging',
    outputDir: 'TomoSubtomo/job030',
    queueSubmit: false,
    nrMpi: 4,
    nrThreads: 4,
    parameters: [
      {
        label: 'Particles STAR file',
        variable: 'fn_data',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Subtomogram particles STAR file',
        nodeType: 'Particles.star',
      },
      {
        label: 'Reference map',
        variable: 'fn_ref',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Reference map',
        nodeType: 'Reference3D.mrc',
      },
      {
        label: 'Symmetry',
        variable: 'sym_name',
        value: 'C1',
        type: 'ANY',
        helpText: 'Point group symmetry',
      },
      {
        label: 'Use GPU acceleration?',
        variable: 'use_gpu',
        value: true,
        type: 'BOOLEAN',
        helpText: 'Use GPU',
      },
      ...createCommonParameters(),
    ],
  },

  [JobType.TOMO_CTFREFINE]: {
    type: JobType.TOMO_CTFREFINE,
    name: 'job031',
    alias: 'Tomo CTF refine',
    outputDir: 'TomoCtfRefine/job031',
    queueSubmit: false,
    nrMpi: 4,
    nrThreads: 4,
    parameters: [
      {
        label: 'Particles STAR file',
        variable: 'fn_data',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Subtomogram particles STAR file',
        nodeType: 'Particles.star',
      },
      {
        label: 'Reference half-map 1',
        variable: 'fn_half1',
        value: '',
        type: 'INPUTNODE',
        helpText: 'First half-map',
        nodeType: 'HalfMap.mrc',
      },
      {
        label: 'Reference half-map 2',
        variable: 'fn_half2',
        value: '',
        type: 'INPUTNODE',
        helpText: 'Second half-map',
        nodeType: 'HalfMap.mrc',
      },
      ...createCommonParameters(),
    ],
  },
};

// Mock pipeline data
export const mockPipeline: Pipeline = {
  name: 'Demo Project',
  projectDir: '/path/to/project',
  lastModified: new Date(),
  processes: [],
  nodes: [],
};

// Mock processes (example workflow)
export const mockProcesses: PipelineProcess[] = [
  {
    id: 'import_001',
    name: 'Import/job001',
    alias: 'Import movies',
    type: JobType.IMPORT,
    status: ProcessStatus.FINISHED_SUCCESS,
    inputNodes: [],
    outputNodes: ['Movies.star'],
  },
  {
    id: 'motioncorr_002',
    name: 'MotionCorr/job002',
    alias: 'Motion correction',
    type: JobType.MOTIONCORR,
    status: ProcessStatus.FINISHED_SUCCESS,
    inputNodes: ['Movies.star'],
    outputNodes: ['corrected_micrographs.star'],
  },
  {
    id: 'ctffind_003',
    name: 'CtfFind/job003',
    alias: 'CTF estimation',
    type: JobType.CTFFIND,
    status: ProcessStatus.RUNNING,
    inputNodes: ['corrected_micrographs.star'],
    outputNodes: ['micrographs_ctf.star'],
  },
];

// Mock process log
export const mockProcessLog: ProcessLog = {
  jobName: 'Example Job',
  stdout: [
    ' RELION version 5.0',
    ' Reading in all input images...',
    ' Processing micrograph 1 of 100...',
    ' Processing micrograph 2 of 100...',
    ' Processing micrograph 3 of 100...',
  ],
  stderr: [],
  lastUpdate: new Date(),
};

// Mock file browser data
export const mockFiles: { name: string; type: 'file' | 'dir' }[] = [
  { name: 'Import', type: 'dir' },
  { name: 'MotionCorr', type: 'dir' },
  { name: 'CtfFind', type: 'dir' },
  { name: 'Class2D', type: 'dir' },
  { name: 'Class3D', type: 'dir' },
  { name: 'Refine3D', type: 'dir' },
  { name: 'default_pipeline.star', type: 'file' },
  { name: '.relion_lock', type: 'file' },
];
